In [1]:
import numpy as np

In [3]:
array1d = np.array([1,2,3])
array2d = np.array([[1,2,3],[4,5,6]])

In [5]:
array1d

array([1, 2, 3])

### ndarray 타입(type)
- ndarray내의 데이터값은 숫자 값, 문자열 값, 불리언 값 등이 모두 가능합니다.
- 숫자형의 경우 int(8bit, 16bit, 32bit), unsigned int형(8bit, 16bit, 24bit), float형(16bit, 32bit, 64bit...), 그리고 이보다 더 큰 숫자값이나 정밀도를 위해 complex타입도 제공합니다.
- nadarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능합니다.(즉, 한개의 ndarray객체에 int와 float가 같이 있을 수 없다.)
- naarray내의 데이터 타입은 ndarray.dtype으로 확인할 수 있다.

In [7]:
### 형태 : shape
print("array1d shape : ",array1d.shape)  ## 1차원
print("array2d.shape : ",array2d.shape)  ## 2차원

array1d shape :  (3,)
array2d.shape :  (2, 3)


In [8]:
### 차원
print("array1d.ndim : ", array1d.ndim)
print("array2d.ndim : ", array2d.ndim)

array1d.ndim :  1
array2d.ndim :  2


In [11]:
list1 = [1,2,3]
print("list1의 타입 : {}".format(type(list1)))
array1 = np.array(list1)
print("array1의 타입 : {}".format(type(array1)))
print("array1.dytpe : {}".format(array1.dtype))

list1의 타입 : <class 'list'>
array1의 타입 : <class 'numpy.ndarray'>
array1.dytpe : int32


 ### ndarray타입(type)변환
 - 변경을 원하는 타입을 astype()에 인자로 입력 (ex : array1d.astype("int32"))
 - 대용량 데이터를 ndarray로 만들 때 메모리를 절약하기 위해 자주 사용 >> 대용량 데이터를 다룰 시 메모리 절약을 위해서 형변환을 특히 고려해야함.

In [16]:
array_int = np.array([1,2,3])
array_float = array_int.astype("float32")

array_int1 = array_float.astype(np.int32)
print("array_int1의 타입 : {}".format(array_int1.dtype))

array_float1 = np.array([1.1, 1.2 ,3.1])
array_int1 = array_float1.astype("int32")
print("array_float1의 타입 : {}".format(array_float1.dtype))

array_int1의 타입 : int32
array_float1의 타입 : float64


### ndarray를 편리하게 생성하기 - arange, zeros, ones
- 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화 생성해야 할 경우 arange(), zeros(), ones()를 이용해 쉽게 ndarray를 생성할 수 있습니다. 주로 **테스트용으로 데이터를 만들거나** 데이터를 일괄적으로 **초기화**해야 할 경우에 사용됩니다.

In [31]:
print("np.arange(10) : {}\n".format(np.arange(10)))
print("np.zeros((3,2), dtype = 'int32' :\n {}\n".format(np.zeros((3,2), dtype = 'int32')))
print("np.ones((3,2)) :\n {}\n".format(np.ones((3,2))))   ### dtype의 default는 float이다.

np.arange(10) : [0 1 2 3 4 5 6 7 8 9]

np.zeros((3,2), dtype = 'int32' :
 [[0 0]
 [0 0]
 [0 0]]

np.ones((3,2)) :
 [[1. 1.]
 [1. 1.]
 [1. 1.]]



##### 실습

In [32]:
### np.arange()
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [37]:
### np.zeros
zero_array = np.zeros((3,2), dtype = np.int32)
print(zero_array)
print(zero_array.dtype, zero_array.shape,'\n')

### np.ones
ones_array = np.ones((3,2), dtype = np.float64)
print(ones_array)
print(ones_array.dtype, ones_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2) 

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()
- reshape()는 ndarray를 특정 차원 및 형태로 변환합니다. 변환 형태를 함수 인자로 부여하면 됩니다.
- reshape(-1,5)와 같이 인자에 -1을 부여하면 -1에 해당하는 axis의 크기는 가변적이되 -1이 아닌 인자값(여기서는 5)에 해당하는 axis 크기는 인자값으로 고정하여 ndarray의 shape를 변환합니다.(ex : 크기가 (10,)인 경우 reshape(-1,5) > (2,5)의 크기가 됨/ 크기가 (15,)인 경우 (3,5)가 됨./ 5로 나눠떨어지지 않으면 오류가 발생한다.)
- reshape(-1,1)과 reshape(-1,)
    - reshape(-1,1) : 2차원으로 변환하되 컬럼 axis 크기가 1로 고정 >> ([0,1,2,3,4] -> [[0], [1], [2], [3], [4]])
    - reshape(-1,) : 1차원으로 변환 >> ([[0], [1], [2], [3], [4]] -> [0,1,2,3,4])

##### 실습

In [41]:
### reshape 해주기
array1 = np.arange(10)
print("array1 : ",array1)

# (2,5) shape로 변환
array2 = array1.reshape(2,5)
print("array2 :\n", array2)

# (5,2) shape로 변환
array3 = array1.reshape(5,2)
print("array3 :\n", array3)

array1 :  [0 1 2 3 4 5 6 7 8 9]
array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [43]:
### (4,3)같은 경우는 바뀔 수 없음
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [47]:
### reshape의 -1
print("array1 : ", array1)

array2 = array1.reshape(-1,5)
print("array2.shape(-1,5) : {}".format(array2.shape))

array3 = array1.reshape(2,-1)
print("array3.shape(2,-1) : {}".format(array3.shape))

array1 :  [0 1 2 3 4 5 6 7 8 9]
array2.shape(-1,5) : (2, 5)
array3.shape(2,-1) : (2, 5)


In [48]:
### 변환이 안되는 경우
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [51]:
### 3차원 ndarray를 1,2차원으로 변환해보기
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print(array3d)
print()

# 3차원 > 2차원
array2d = array3d.reshape(-1,1)
print(array2d)
print()

# 1차원 > 2차원
array2d_2 = array1.reshape(-1,1)
print(array2d_2)
print()

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]



In [54]:
# 3차원 > 1차원
array3to1 = array3d.reshape(-1,)
print(array3to1)

[0 1 2 3 4 5 6 7]


### 인덱싱

- 특정 위치의 단일값 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환됩니다.
- 슬라이싱 : 슬라이싱은 연속된 인덱스상의 ndarray를 추출하는 방식입니다. : 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1 위치에 있는 ndarray를 반환합니다.
- 팬시 인덱싱 : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 ndarray를 반환합니다. (ex : array1[[2,4,7]])
- **불린 인덱싱** : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 ndarray를 반환합니다.(조건 필터링 및 추출)

##### 단일 인덱싱

In [3]:
array1 = np.arange(start= 1, stop = 10)
print("array1 : {}".format(array1))

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값 의미
value = array1[2]
print("value : {}".format(value))
print("value의 타입 : {}".format(type(value)))  ## 인덱싱은 차원을 줄여준다.

array1 : [1 2 3 4 5 6 7 8 9]
value : 3
value의 타입 : <class 'numpy.int32'>


In [8]:
## -인덱싱
print("맨 뒤의 값 : {}, 맨 뒤에서 두번째 값 : {}".format(array1[-1], array1[-2]))

맨 뒤의 값 : 9, 맨 뒤에서 두번째 값 : 8


In [11]:
## 2차원 인덱싱
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3,3)
print(array2d)
print()
print("(row = 0, col = 0) index 가리키는 값 : {}".format(array2d[0,0]))
print("(row = 0, col = 1) index 가리키는 값 : {}".format(array2d[0,1]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

(row = 0, col = 0) index 가리키는 값 : 1
(row = 0, col = 1) index 가리키는 값 : 2


##### 슬라이싱 인덱스

In [15]:
array1 = np.arange(start = 1, stop = 10)
print("array1 : {}".format(array1))

array3 = array1 [0:3]
print("array3 : {}".format(array3))
print("array3의 타입 : {}".format(type(array3)))  ## 슬라이싱은 차원이 줄어들지 않는다.

array1 : [1 2 3 4 5 6 7 8 9]
array3 : [1 2 3]
array3의 타입 : <class 'numpy.ndarray'>


In [17]:
# 위치 인덱스 0-2(2포함)까지 추출
array4 = array1[0:3]
print(array4)
print()

# 위치 인덱스 3부터 마지막까지 추출
array5 = array1[3:]
print(array5)
print()

# 위치 인덱스로 전체 데이터 추출
array6 = array1[:]
print(array6)

[1 2 3]

[4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]


In [21]:
print(array2d)
print()

print("array2d[0:2, 0:2] \n", array2d[0:2, 0:2])
print()
print("array2d[:2, 0] \n", array2d[:2, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]

array2d[:2, 0] 
 [1 4]


In [22]:
# 2차원 단일인덱싱 > 행만 추출
print(array2d[0])
print(array2d[1])

[1 2 3]
[4 5 6]


##### 펜시 인덱싱

In [29]:
array1d = np.arange(start = 1 , stop = 10)
array2d = array1d.reshape(3,3)
print(array2d)
print()
array3 = array2d[[0,1],2]
print("array2d[[0,1],2] : ", array3)
print()
array4 = array2d[[0,2],:2]
print("array2d[[0,2],:2] : ", array4)
print()

array5 = array2d[[0,2]]
print("array2d[[0,2]] : ", array5)
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[[0,1],2] :  [3 6]

array2d[[0,2],:2] :  [[1 2]
 [7 8]]

array2d[[0,2]] :  [[1 2 3]
 [7 8 9]]



##### 불린 인덱싱

In [31]:
print(array1d)

# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d>5]
print("array1d>5 불린 인덱싱 결과 값 : ", array3)

[1 2 3 4 5 6 7 8 9]
array1d>5 불린 인덱싱 결과 값 :  [6 7 8 9]


In [32]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [33]:
val = array1d>5
print(val, type(val), val.shape)

[False False False False False  True  True  True  True] <class 'numpy.ndarray'> (9,)


In [34]:
## true에 해당하는 index값만 저장해 값을 추출함
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print("불리언 인덱스로 필터링 결과 :", array3)

불리언 인덱스로 필터링 결과 : [6 7 8 9]


In [35]:
## 일반 인덱스(펜시 인덱스)를 사용한 결과
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print("일반 인덱스로 필터링 결과 : ", array4)

일반 인덱스로 필터링 결과 :  [6 7 8 9]


### 배열의 정렬 - sort()와 argsort()

##### 넘파이 sort() 유형
- np.sort(ndarray) : 인자로 들어온 **원 행렬은 그대로 유지**한 채 원 행렬의 정렬된 행렬을 반환
- ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 반환값은 None
- np.sort()나 ndarray.sort() 모두 기본적으로 오름차순으로 행렬 내 원소를 정렬합니다. 내림차순으로 정렬하기 위해서는 [::-1]을 적용합니다.(ex : np.sort()[::-1])

##### 2차원 배열에서 axis 기반의 sort()
- axis = 0인 경우 행을 정렬
- axis = 1인 경우 열을 정렬

##### argsort()
- 원본 행렬 정렬 시 정렬된 행렬의 원래 인덱스를 필요로 할 때 np.argsort()를 이용합니다. np.argsort()는 정렬 행렬의 **원본 행렬 인덱스**를 ndarray형으로 반환합니다.

##### 실습

In [5]:
### 넘파이 sort
org_array = np.array([3,1,9,5])
print("원본 배열 : ", org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print("np.sort() 호출 후 반환된 정렬 배열 : ", sort_array1)
print("np.sort() 호출 후 원본 배열 : ", org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print("ndarray.sort() 호출 후 반환된 정렬 배열 : ", sort_array2)  ### ndarray.sort()의 경우 반환되는 값이 없다.
print("ndarray.sort() 호출 후 원본 배열: ", org_array)

원본 배열 :  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 배열 :  [1 3 5 9]
np.sort() 호출 후 원본 배열 :  [3 1 9 5]
ndarray.sort() 호출 후 반환된 정렬 배열 :  None
ndarray.sort() 호출 후 원본 배열:  [1 3 5 9]


In [11]:
### 내림차순의 정렬
sort_array_desc1 = np.sort(org_array)[::-1]
print("내림차순으로 정렬 : ", sort_array_desc1)

내림차순으로 정렬 :  [9 5 3 1]


In [16]:
### 2차원 배열의 정렬
array2d = np.array([[8, 1],
                   [7, 12]])

sort_array2d_axis0 = np.sort(array2d, axis = 0)  ## array2d.sort(axis = 0)으로도 가능
print("로우 방향으로 정렬 :\n", sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print("컬럼 방향으로 정렬 :\n", sort_array2d_axis1)

로우 방향으로 정렬 :
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬 :
 [[ 1  8]
 [ 7 12]]


In [17]:
### argsort : 정렬 행렬의 인덱스 반환
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print("행렬 정렬 시 원본 배열의 인덱스 : ", sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 배열의 인덱스 :  [1 0 3 2]


In [19]:
### argsort : 정렬 행렬의 인덱스 반환(내림차순)
sort_indices_desc = np.argsort(org_array)[::-1] ### org_array.argsort()도 가능
print(type(sort_indices_desc))
print("행렬 내림차순 정렬시 원본 배열의 인덱스 : ", sort_indices_desc)

<class 'numpy.ndarray'>
행렬 내림차순 정렬시 원본 배열의 인덱스 :  [2 3 0 1]


In [9]:
### argsort 적용
import numpy as np

name_array = np.array(["jhon", "mike" , 'sarah', 'kate', 'samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print("성적 오름차순 정렬 시 score_array의 인덱스 : ", sort_indices_asc)
print("성적 오름차순으로 name_array의 이름 출력 : ", name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 :  [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력 :  ['jhon' 'sarah' 'samuel' 'mike' 'kate']


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [10]:
### 행렬 내적
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[7,8],
             [9,10],
             [11, 12]])

dot_prd = np.dot(a,b)
print("행렬 내적 결과 : \n", dot_prd)

행렬 내적 결과 : 
 [[ 58  64]
 [139 154]]


In [15]:
### 전치 행렬 구하기
transpose_mat = np.transpose(a)
print("원래 a 행렬 :\n", a)
print()
print("a의 전치 행렬 : \n", transpose_mat)

원래 a 행렬 :
 [[1 2 3]
 [4 5 6]]

a의 전치 행렬 : 
 [[1 4]
 [2 5]
 [3 6]]
